# Travis CI(http://travis-ci.org) configuration file
#  https://docs.travis-ci.com/user/languages/python/
language: python
dist: bionic

python:
- 2.7
- &latest_py3 3.9

cache: pip

before_install:
  # Git test setup
  - git config --global user.name "Git Cola"
  - git config --global user.email git-cola@localhost.localdomain
  - sudo apt update
  # Build dependencies
  - sudo apt install -y gettext
  - sudo apt install -y rsync
  - sudo apt install -y python-sphinx
  - sudo apt install -y python3-sphinx
  # Runtime dependencies
  - sudo apt install -y python-pyqt5
  - sudo apt install -y python3-pyqt5
  # Test dependencies
  - sudo apt install -y python3-venv

install:
  # Build translations
  - make all

before_script:
  - pip install tox tox-venv

script:
  - tox
  - tox -e pylint
