# Travis CI(http://travis-ci.org) configuration file
#  https://docs.travis-ci.com/user/languages/python/
language: generic
dist: bionic
sudo: required

before_install:
  # Git test setup
  - git config --global user.name "Git Cola"
  - git config --global user.email git-cola@localhost.localdomain
  - sudo apt update
  # Build dependencies
  - sudo apt install -y gettext
  - sudo apt install -y rsync
  - sudo apt install -y python-sphinx
  - sudo apt install -y python3-sphinx
  # Runtime dependencies
  - sudo apt install -y python-pyqt5
  - sudo apt install -y python3-pyqt5
  # Test dependencies
  - sudo apt install -y tox

install:
  # Build translations
  - make all

script:
  # Tests and static analysis checks
  - tox -v --develop --skip-missing-interpreters -e "py{27,36},pylint{2,36}"
