# Travis CI(http://travis-ci.org) configuration file
#  https://docs.travis-ci.com/user/languages/python/
language: python
dist: bionic
sudo: required
python:
  - "2.7"
  - "3.6"
virtualenv:
  system_site_packages: true

before_install:
  # Git test setup
  - git config --global user.name "Git Cola"
  - git config --global user.email git-cola@localhost.localdomain
  - sudo apt update
  # Build dependencies
  - sudo apt install -y gettext
  - sudo apt install -y rsync
  - sudo apt install -y python-sphinx
  - sudo apt install -y python3-sphinx
  # Runtime dependencies
  - sudo apt install -y python-pyqt5
  - sudo apt install -y python3-pyqt5

install:
  # Test dependencies
  - make requirements-dev
  # Build translations
  - make all

script:
  # Run tests and static analysis checks
  - make check V=2
