# Travis CI(http://travis-ci.org) configuration file
language: python
python:
  - "2.7"
  - "3.4"
#  https://docs.travis-ci.com/user/languages/python/
#  We use apt to avoid having to build PyQt ourselves, so that means
#  we can only use the default python versions available in Ubuntu.
#  For Trusty, that's 2.7.6 and 3.4.3.
virtualenv:
  system_site_packages: true

# git and python are pre-installed
before_install:
  # Update APT cache data since it may outdated
  - sudo apt-get -qq update
  # according to Debian control file from Ubuntu 12.04
  - sudo apt-get install -y git rsync gettext
  # Runtime dependencies
  - sudo apt-get install -y python-qt4
  - sudo apt-get install -y python3-pyqt5
  # Build/test dependencies
  - sudo apt-get install -y python-sphinx python3-sphinx
  - sudo apt-get install -y pylint
  # Git test setup
  - git config --global user.name "Git Cola"
  - git config --global user.email git-cola@localhost.localdomain

install:
  # Build dependencies
  - make requirements
  # Test dependencies
  - make requirements-dev

script:
  - make all
  - make test V=2
  - make doc
  - pylint --version
  - test "2.7" != "$TRAVIS_PYTHON_VERSION" || make pylint
  - make pylint3k
  - flake8 --version
  - make flake8
