package:
  name: qtpy
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_url: ../
  git_tag: {% if environ.get('PRERELEASE') == 'True' %} master {% else %} {{ environ.get('GIT_DESCRIBE_TAG') }} {% endif %}

build:
  noarch_python: True
  number: {% if environ.get('PRERELEASE') == 'True' %} {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }} {% else %} 0 {% endif %}

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - qtpy
  requires:
    - pyqt

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  summary: Provides an uniform layer to support PyQt4, PyQt5 and PySide with a single codebase
